### PR TITLE
patch newly created buffers, too

### PR DESCRIPTION
**Pull request by ritschwumm**

### CODE REVIEW

**Comment by xuhdev** [comment]
Could you briefly explain the issue you are encountering please?

**Comment by ritschwumm** [comment]
well, after creating a new buffer, its settings are still on the default value configured in jEdit and not what's configured in my .editorconfig. saving, closing and re-opening the buffer helps, but that became tedious :)

**Comment by xuhdev** [comment]
I no longer have jEdit installed and it may take me quite a while to figure out what's going on :) Would jEdit know the path to the buffer if it's newly created? This may affect how `.editorconfig` files are loaded.

**Comment by ritschwumm** [comment]
hm, you are right, it's not ideal: 
new buffers, being named "Untitled-1" _do_ get configured with my [*] configuration, but stay at those settings after saving them with a file name that should have different settings. well - at least i don't accidentally check in files using TABs at work any more, but this is not good enough.
i wonder if i should patch on save, too...

**Comment by xuhdev** [comment]
Perhaps it's better idea to update the settings on first save, so that the path is clear.

**Comment by ritschwumm** [comment]
just tried to put that on BufferUpdate.SAVING - funnily, that does _not_ work as expected:
i create a buffer, immediately save it - properties are still the default ones.
i save it _again_, and now everything is fine. back to the drawing board...

**Comment by ritschwumm** [comment]
oh - and thanks for the prompt reaction, that was much quicker than i'd have expected :)

**Pull request closed without merging**
